# Generated by Django 3.1.7 on 2021-03-22 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import realty.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'amenity',
                'verbose_name_plural': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('is_available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('realty_type', models.CharField(choices=[('House', 'House'), ('Hotel', 'Hotel Room'), ('Apartments', 'Apartments')], default='Apartments', max_length=31, verbose_name='type of the realty')),
                ('beds_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='beds count')),
                ('max_guests_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('price_per_night', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amenities', models.ManyToManyField(blank=True, related_name='realty', to='realty.Amenity', verbose_name='amenities')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realty', to='hosts.realtyhost', verbose_name='realty host')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addresses.address', verbose_name='location')),
            ],
            options={
                'verbose_name': 'realty',
                'verbose_name_plural': 'realty',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='RealtyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=realty.models.get_realty_image_upload_path, verbose_name='image')),
                ('realty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='realty.realty', verbose_name='realty image')),
            ],
            options={
                'verbose_name': 'Realty image',
                'verbose_name_plural': 'Realty images',
            },
        ),
    ]
