# Generated by Django 3.1.7 on 2021-03-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtyimage',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='realty.realty', verbose_name='realty'),
        ),
    ]
