# Generated by Django 3.1.7 on 2021-03-27 10:17

from django.db import migrations
import realty.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20210326_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtyimage',
            options={'ordering': ('order',), 'verbose_name': 'Realty image', 'verbose_name_plural': 'Realty images'},
        ),
        migrations.AddField(
            model_name='realtyimage',
            name='order',
            field=realty.fields.OrderField(blank=True, null=True),
        ),
    ]
