# Generated by Django 3.1.7 on 2021-03-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20210327_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='realty_type',
            field=models.CharField(choices=[('House', 'House'), ('Hotel', 'Hotel'), ('Apartments', 'Apartments')], default='Apartments', max_length=31, verbose_name='type of the realty'),
        ),
    ]
