# Generated by Django 3.1.7 on 2021-03-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20210327_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
