# Generated by Django 3.1.7 on 2021-05-03 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_realtyview'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtyView',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('is_available', models.BooleanField(default=False, verbose_name='is realty available')),
                ('realty_type', models.CharField(choices=[('House', 'House'), ('Hotel', 'Hotel'), ('Apartments', 'Apartments')], default='Apartments', max_length=31, verbose_name='type of the realty')),
                ('beds_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='beds count')),
                ('max_guests_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('price_per_night', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('country', models.CharField(max_length=255, verbose_name='location country')),
                ('city', models.CharField(max_length=255, verbose_name='location city')),
                ('street', models.CharField(max_length=255, verbose_name='location street')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='host email')),
                ('first_name', models.CharField(max_length=40, verbose_name='host first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='host last name')),
            ],
            options={
                'db_table': 'realty_view',
                'managed': False,
            },
        ),
    ]
