# Generated by Django 3.1.7 on 2021-05-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_realtyview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realty',
            name='amenities',
        ),
        migrations.AddField(
            model_name='realty',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='realty', to='realty.Amenity', verbose_name='amenities'),
        ),
    ]
