# Generated by Django 3.1.7 on 2021-05-23 19:09

from django.db import migrations
import realty.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0011_auto_20210523_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtyimage',
            options={'ordering': ('order',), 'verbose_name': 'realty image', 'verbose_name_plural': 'realty images'},
        ),
        migrations.AlterField(
            model_name='realtyimage',
            name='order',
            field=realty.fields.OrderField(blank=True, null=True, verbose_name='order'),
        ),
    ]
