# Generated by Django 3.1.7 on 2021-05-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20210413_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'subscriber', 'verbose_name_plural': 'subscribers'},
        ),
    ]
