# Generated by Django 3.1.7 on 2021-03-22 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtyhost',
            name='description',
            field=models.TextField(blank=True, verbose_name='host description'),
        ),
        migrations.AlterField(
            model_name='realtyhost',
            name='host_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating'),
        ),
    ]
