# Generated by Django 3.1.7 on 2021-03-23 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20210322_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyhost',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of birth'),
            preserve_default=False,
        ),
    ]
