# Generated by Django 3.1.7 on 2021-04-16 20:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210416_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_code', models.CharField(blank=True, max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='4 digits sms code')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_log', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'sms log',
                'verbose_name_plural': 'sms logs',
            },
        ),
    ]
