# Generated by Django 3.1.13 on 2021-10-30 10:31

import accounts.models
import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210523_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default=accounts.models.get_default_profile_image, null=True, storage=common.utils.select_file_storage, upload_to=accounts.models.get_profile_image_upload_path, verbose_name='profile image'),
        ),
    ]
