# Generated by Django 3.1.7 on 2021-04-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210411_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='email confirmed'),
        ),
    ]
