# Generated by Django 3.1.7 on 2021-04-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_phone_number_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
