# Generated by Django 3.1.7 on 2021-05-23 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0010_auto_20210504_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='max_guests_count',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='maximum guests amount'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='price_per_night',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='price per night'),
        ),
    ]
