# Generated by Django 3.1.7 on 2021-07-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0012_auto_20210523_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='visits_count',
            field=models.PositiveIntegerField(default=0, verbose_name='visits count'),
        ),
    ]
